# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('common_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('autologin', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('CA', 'ca'), ('TL', 'tls_auth'), ('DH', 'dh'), ('RL', 'crl'), ('SV', 'server'), ('CL', 'client')], default='CL', max_length=2, verbose_name='Type')),
                ('next_serial_number', models.IntegerField(blank=True, null=True)),
                ('key_size', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('cert', models.TextField(blank=True)),
                ('priv_key', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
